sudo: false

language: go

go:
- "1.10.x"

before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_deploy:
- git config --local user.name "Michael Laccetti"
- git config --local user.email "michael@laccetti.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: "EeyvDrS8U7OQGbS4b9GEVxApj/yzzW1FGSXlcoZ60FKCF6e1xFIB0foC4KOn571CHZebejAHWMX8B7C1RfPH4YKsLFPouP/eO/qFTMxY0a0j/pG6akGLMLUROGF5gm5hkHMFKItnyZhj1f76zZ96hTshZYz6ZxtnvI+vvpETSC3G2+FYGRBmzQIC7e+/hKea6+LZg4qBHMtXiGs2Te2j8+k76iC0dgx9PXw8lSMUD6HnT4l8WH4+g+gobIcjUhv3A/WxyY7Prm7TW6KkZrgbagrbBiXOv+u2sXmeV8qnargFoTnKKcAgfBNDeSqIccI6+YfG3d6VcdAbZ+SR/pxjCkmDdFoYiXQEktpdVZ7lH8ojjPnh6PfZnY5UL/4ThPQLgkV20psPuM4/bKU/HW9dhDHjjWnxsQD5sH9ldsv0vNaYfGPODIoedEJLw3C/7/vAOsYWcQ8VRCnvwqi9a+Ja+solk8YdFXQphwsaE0l3QO8xJqWPCgJzSWxCENU6/CQFLkQEh8gUpyA74x/xkPRrQmMHh+lcwcNtqjVMCQ0lK0zTW4ynWVvsZwKmj+YIn8O1k90EllWUcxvjI2PPzhYdnXnOuymIgwjG6SvlEEKsctxPQS5v/kaNfR302M8GdT5uA6tR8KesQ3uepwwO9Dp8AZeo2q4A+BGLxJQwpPhqnKY="
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
