[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/oschwald/geoip2-golang"
  version = "1.2.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
