replicaCount: 1

image:
  repository: mlaccetti/ipd2
  tag: 0.1.2
  pullPolicy: IfNotPresent

service:
  http:
    type: ClusterIP
    port: 80
  https:
    enabled: false
    type: ClusterIP
    port: 443

ingress:
  hosts:
    - chart-example.local
  path: /
  http:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
  https:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    tls:
      secretName: chart-example-tls

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
